#!/usr/bin/env bash

RUN_ZSH=false

if ! command -v zsh &> /dev/null
then
    RUN_ZSH=true
    if command -v apt &> /dev/null
    then
        sudo apt update
        sudo apt install zsh -y
    elif command -v zypper &> /dev/null
    then
        sudo zypper install -y zsh
    fi

    chsh -s $(which zsh)
fi

if ! command -v fzf &> /dev/null
then
    if command -v apt &> /dev/null
    then
        sudo apt update
        sudo apt install fzf -y
    elif command -v zypper &> /dev/null
    then
        sudo zypper install -y fzf
    fi
fi

if ! command -v keychain &> /dev/null
then
    if command -v apt &> /dev/null
    then
        sudo apt update
        sudo apt install keychain -y
    elif command -v zypper &> /dev/null
    then
        sudo zypper install -y keychain
    fi
fi

if [ ! -d $HOME/.oh-my-zsh ]
then
    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc
fi

if [ ! -d ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k ]
then
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
fi

if RUN_ZSH
then
    exec zsh -l
fi
